# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "ru-simple-technical-resume"
version = "0.1.1"
entrypoint = "src/lib.typ"
authors = ["Himank Dave <https://steadyfall.github.io/>", "Sergei Makhinov <https://sermah.dev/>"]
license = "MIT"
description = "A russian fork of simple-technical-resume. A simple technical resume designed to fit within a page and work well with ATS."
repository = "https://github.com/sermah/ru-simple-technical-resume-template"
keywords = ["cv", "resume", "technical", "ATS", "russian", "ru"]
categories = ["cv"]
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "example.pdf",
  "example.png",
]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
